### ISSUE TITLE
Bangs don't work.

### ISSUE THREAD

**Issue by NutZach** [RobertFrydenlund/SpotifyPlugin#7] opened 2018-04-29 03:13 UTC
Either I'm dumb or bangs don't work. But as far as I can tell the bangs don't function.  I used the test script in the readme and tried it myself.

Edit: I may have an older version, let me check.
Edit2: Well, I had 1.3.  I have version 1.9 (please let me know if its not the latest) and bangs still don't work.

**Comment by khanhas** [comment] 2018-04-29 03:38
https://github.com/RobertFrydenlund/SpotifyPlugin/releases

**Comment by MarcoPixel** [comment] 2018-04-29 09:06
@NutZach What @khanhas is trying to say is that 1.9 is a pretty old version and you should go to the link he posted above and install the latest version by downloading the rmskin file and then installing the example skin.

**Comment by NutZach** [comment] 2018-04-29 13:53
Thanks for showing me the latest version, but neither my own or the example bangs work after I downloaded the update.

**Comment by NutZach** [comment] 2018-04-29 13:55
This is the test code I'm using.
`[MeasureCover]
Measure=Plugin
Plugin=SpotifyPlugin
Type=AlbumArt
Res=300
DefaultPath=#@#Default.png
CoverPath=#@#Cover.png

[MeasureProgress]
Measure=Plugin
Plugin=SpotifyPlugin
Type=Progress

 [MeterCover]
 Meter=Image
 ImageName=[MeasureCover]
 LeftMouseUpAction=[!CommandMeasure "MeasureProgress" "PlayPause"]
 X=0
 Y=0
 W=300
 H=300
 DynamicVariables=1`

**Comment by RobertFrydenlund** [comment] 2018-04-30 12:46
@NutZach Please install [version 2.1.4](https://github.com/RobertFrydenlund/SpotifyPlugin/releases/tag/v2.1.4) and try again. If it doesn't work, right-click rainmeter > logging > show log file, then post it here.

**Comment by NutZach** [comment] 2018-04-30 22:03
@RobertFrydenlund 

`ERRO (16:43:20.766) : Object reference not set to an instance of an object. at SpotifyPlugin.Measure.<>c__DisplayClass10_0.<ExecuteBang>b__0()`

When I click a button coded with a bang it will lag the skin for a half second, then nothing happens.

That's the only thing I found in the log file that was an error.  I tried multiple times but it only showed up once.  Here's a bang from my skin if you would like to check to make sure it's coded right.:

```
[Skip]
meter=image
imagename=#@#Skip.png
LeftMouseUpAction=[!CommandMeasure "RawProgress" "Next"]
x=502
y=0
h=100
w=100
ImageTint=#Grey#
```

And RawProgress is this measure.

```
[RawProgress]
Measure=Plugin
Plugin=SpotifyPlugin
Type=Progress
```

**Comment by RobertFrydenlund** [comment] 2018-04-30 22:57
@NutZach It seems like it cant set up the WebAPI properly. You don't happen to use AVG? It has blocked this plugin before. Try pausing your firewall to see if it works. If you log into Spotify on their web page you can also administer apps with access to your account. See if SpotifyPlugin is listed there.

**Comment by NutZach** [comment] 2018-05-01 00:36
Spotify Plugin is in authorized apps and I only use Windows Defender.  WD is supposed to warn me not block, so I doubt it's that.  Is there anything else that can shut down the WebAPI?

**Comment by MarcoPixel** [comment] 2018-05-01 00:44
@NutZach Also try using Google DNS as i've had issues with that before too.

**Comment by NutZach** [comment] 2018-05-02 00:59
@RobertFrydenlund Found this while debugging my skin.

```
7:29:16 PM Tuesday, May 1, 2018
SpotifyPlugin version 2.1.4.0
Culture: en-US
OSVersion: Microsoft Windows NT 10.0.16299.0
----
 The remote server returned an error: (404) Not Found.
----
    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)

   at System.Net.WebClient.DownloadString(Uri address)

   at SpotifyPlugin.AlbumArt.GetAlbumImage(Int32 resolution, String filePath)
```

**Comment by RobertFrydenlund** [comment] 2018-05-02 01:45
@NutZach That shouldn't stop bangs from working. It should just not find an album cover for you. Have you tried what @MarcoPixel suggested?

**Comment by RobertFrydenlund** [comment] 2018-07-05 20:50
Closing this as the issue is fairly old now. If the problem still persists, open a new issue.

**Closed by RobertFrydenlund** 2018-07-05 20:50 UTC
